# Tokyo Night Theme for Yazi

[manager]
cwd = { fg = "#7aa2f7" }

# Hovered
hovered         = { fg = "#15161e", bg = "#7aa2f7" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#e0af68", italic = true }
find_position = { fg = "#ff007c", bg = "reset", italic = true }

# Marker
marker_copied   = { fg = "#9ece6a", bg = "#9ece6a" }
marker_cut      = { fg = "#f7768e", bg = "#f7768e" }
marker_marked   = { fg = "#7dcfff", bg = "#7dcfff" }
marker_selected = { fg = "#7aa2f7", bg = "#7aa2f7" }

# Tab
tab_active   = { fg = "#15161e", bg = "#7aa2f7" }
tab_inactive = { fg = "#a9b1d6", bg = "#24283b" }
tab_width    = 1

# Count
count_copied   = { fg = "#15161e", bg = "#9ece6a" }
count_cut      = { fg = "#15161e", bg = "#f7768e" }
count_selected = { fg = "#15161e", bg = "#7aa2f7" }

# Border
border_symbol = "│"
border_style  = { fg = "#565f89" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#24283b", bg = "#24283b" }

# Mode
mode_normal = { fg = "#15161e", bg = "#7aa2f7", bold = true }
mode_select = { fg = "#15161e", bg = "#bb9af7", bold = true }
mode_unset  = { fg = "#15161e", bg = "#f7768e", bold = true }

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#7aa2f7", bg = "#24283b" }
progress_error  = { fg = "#f7768e", bg = "#24283b" }

# Permissions
perm_type  = { fg = "#7aa2f7" }
perm_read  = { fg = "#e0af68" }
perm_write = { fg = "#f7768e" }
perm_exec  = { fg = "#9ece6a" }
perm_sep   = { fg = "#565f89" }

[input]
border   = { fg = "#7aa2f7" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#7aa2f7" }
active   = { fg = "#bb9af7" }
inactive = {}

[tasks]
border  = { fg = "#7aa2f7" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#24283b" }
cand            = { fg = "#7aa2f7" }
rest            = { fg = "#565f89" }
desc            = { fg = "#bb9af7" }
separator       = "  "
separator_style = { fg = "#565f89" }

[help]
on      = { fg = "#7aa2f7" }
run     = { fg = "#bb9af7" }
desc    = { fg = "#565f89" }
hovered = { bg = "#414868", bold = true }
footer  = { fg = "#a9b1d6", bg = "#24283b" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#7dcfff" },

	# Videos
	{ mime = "video/*", fg = "#e0af68" },
	{ mime = "audio/*", fg = "#e0af68" },

	# Archives
	{ mime = "application/*zip", fg = "#bb9af7" },
	{ mime = "application/x-tar", fg = "#bb9af7" },
	{ mime = "application/x-bzip", fg = "#bb9af7" },
	{ mime = "application/x-bzip2", fg = "#bb9af7" },
	{ mime = "application/x-7z-compressed", fg = "#bb9af7" },
	{ mime = "application/x-rar", fg = "#bb9af7" },
	{ mime = "application/x-xz", fg = "#bb9af7" },

	# Documents
	{ mime = "application/doc", fg = "#9ece6a" },
	{ mime = "application/pdf", fg = "#9ece6a" },
	{ mime = "application/rtf", fg = "#9ece6a" },
	{ mime = "application/vnd.*", fg = "#9ece6a" },

	# Fallback
	{ name = "*", fg = "#a9b1d6" },
	{ name = "*/", fg = "#7aa2f7" }
]
